println ("Hallo mijn naam is");
println ("Ninjo de bandjo");
println (" ");
println ("Ik ben 22 jaar oud");
println ("En al 4 jaar student");
println (" ");
println ("Ik kom uit Almere en doe deze opleiding omdat:");
println ("Het altijd al iets is geweest dat me leuk lijkt");
println ("Ik weet niet wat ik hier verder moet zetten");
println (" ");
println ("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum");
println ("Ik");
println ("    Doe");
println ("          Iets");
println ("                 Random");
